"""Add inventory

Revision ID: a52392466e81
Revises: f6e3f43f02ba
Create Date: 2020-10-10 15:27:51.214343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a52392466e81"
down_revision = "f6e3f43f02ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "items",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cost", sa.Integer(), nullable=True),
        sa.Column("creation_id", sa.BIGINT(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_items")),
        sa.UniqueConstraint("name", name=op.f("uq_items_name")),
    )
    op.create_table(
        "inventories",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("player_id", sa.BIGINT(), nullable=True),
        sa.Column("item_id", sa.BIGINT(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("fk_inventories_item_id_items")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_inventories_player_id_players")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventories")),
    )
    op.add_column(
        "planted_crops", sa.Column("last_watered", sa.DateTime(), nullable=True)
    )
    op.add_column("planted_crops", sa.Column("stage", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("planted_crops", "stage")
    op.drop_column("planted_crops", "last_watered")
    op.drop_table("inventories")
    op.drop_table("items")
    # ### end Alembic commands ###
